### ISSUE TITLE
Secret for Public Clients

### ISSUE THREAD

**Issue by legitimoth** [ferrerojosh/nest-keycloak-connect#112]
I would like to know how we do to set secret when our client is Public. I don't have a secret and it's required on KeycloakConnectOptions .

I've tried let it empty '' and set public-client as true and public as true but, nothing work.

**Comment by ferrerojosh** [comment]
I assumed nestjs as a backend application only when creating this library. Is this a use-case for a static serving application ? It's the only use-case I can think of when setting client to public since it would serve html pages in which you can do a login.

**Comment by MoacirCarlos** [comment]
I have the same problem, the workaround I found was to work with 2 clients, the public one for the frontend and the confidential one for the backend.

Kind of meaningless, because the token generated in the public has to be valid for the backend which is confidential...

**Comment by olee** [comment]
Same issue here. This is actually quite annoying as it forces me to use a secret also for the frontend client which it does not actually require, or do it as @MoacirCarlos did and define 2 clients.

Is there any alternative solution to this yet?

**Comment by ferrerojosh** [comment]
I am confused as to what we are trying to accomplish here.

So in a standard setup, we have two clients:
- Web/Mobile App (Public)
- Trusted Backend (Needs Secret, in which this library is mostly used for)
- Authentication Provider (Keycloak)

The public facing client needs a user to authenticate in order to get a token. The trusted backend needs a secret to authenticate to the auth provider; to verify the tokens it receives from the client to the auth provider.

Keycloak **requires a secret to utilize its AuthZ** feature. This might be the thing that confuses everyone. If you're merely using this for roles authorization, please use a standard oauth2 library, Keycloak has full support for the specification. Passport will do its job quite well for role-based claims authorization.
