### ISSUE TITLE
keycloak-nodejs-connect 25.0.0 support

### ISSUE THREAD

**Issue by moisesrodriguez** [ferrerojosh/nest-keycloak-connect#189]
Recenctly [keycloak-nodejs-connect](https://github.com/keycloak/keycloak-nodejs-connect) has released version 25.0.0. Is it planned to support version 25.0.0 on this adapter?

**Comment by ferrerojosh** [comment]
Most version changes are just dependency and version bumps, I'm always checking after a major bump for any breaking changes but so far the Keycloak team has done nothing of the sort. It is also due to the fact that they deprecated the library and it just aligning the versions apparently.

Anyway don't mind the yap, will be updating peer dependencies as soon as I can.
