### ISSUE TITLE
breaking changes  are introduced in minor version upgrage

### ISSUE THREAD

**Issue by erald14** [ferrerojosh/nest-keycloak-connect#78]
1.7.0 breaks existing apps. 
changing to 2.0 is  advised  for breaking changes like this, since package managers automatically upgrade to latest minor version

**Comment by EFritzsche90** [comment]
Agree, but this could be told much more nicer than you did. He did a really great work and we should appreciate that instead of blaming him.

**Comment by diogomoreira** [comment]
I agree. I've been following a tutorial that indicates this library using version `1.2.1`, I tried to install version `1.7.1` and it wasn't possible by the Nest version (which even, I don't know why 8 is necessary, but honestly, I would like to know). I tried version `1.6.1` and it no longer has some of the features indicated in the tutorial (like `@AllowAnyRole()` annotation).

I write this comment not as a criticism or demand for changes, but I believe that the library's objective is very good and a guideline for changes should be followed.

**Comment by erald14** [comment]
Sorry If I came through as blaming, I was very tired because I wasted a good amount of hours until I found out the issue was coming from this package, so I didn't pay much attention to the wording. Normally you wouldn't think this would be an issue since breaking changes are introduced in major version upgrades.

**Comment by EFritzsche90** [comment]
Perfect. So @ferrerojosh let's try to follow the standard versioning, so that no one is wasting time on unexpected changes. :)

**Comment by ferrerojosh** [comment]
My bad. I actually put a note in the release logs that I might remove the necessary need for NestJS 8 if needed be.

I didn't bump the major version since there should be no compatibility issues with the current public api but I guess the mandatory dependency to NestJS 8 broke most builds so that is on me.

Thank you for your inputs, I freely welcome this kind of feedback.

**Comment by MarkPieszak** [comment]
Just chiming in as well! Yes I got a similar error (in a NestJS v7 app) stating that yes ConsoleLogger is not a Constructor, and after some digging realized yes it was because it's depending on v8 which isn't installed.

Just for reference, this line specifically in `keycloak-connect.providers`

![image](https://user-images.githubusercontent.com/2574412/129101171-cc4a6fe2-2cad-4ed0-9052-3f2888ec7fba.png)

Bumping down for now until a new patch version 1.7.x is released with v7 support :+1:

**Comment by erald14** [comment]
@ferrerojosh  so now 1.7 is not breaking with nest 7?

**Comment by ferrerojosh** [comment]
> @ferrerojosh so now 1.7 is not breaking with nest 7?

Yes it should work now since I reverted the need for NestJS 8 (I re-introduced the wrapper logger)

**Comment by erald14** [comment]
thanks
