### ISSUE TITLE
How to do "confidential" client works authenticating over the keycloak login page?

### ISSUE THREAD

**Issue by rordenerena** [ferrerojosh/nest-keycloak-connect#85]
I have read the book from keycloak creators and I have some examples working right with my realm and app client over nodejs.

But I want to use nestjs instead of nodejs, then I'm using your npm module, but, i cannot going work an example with a confidential app client (nodejs official example: https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/tree/master/ch7/nodejs/frontend) configured in kc, ie, if I dont have a bearer token or session, the backend should be redirect to keycloak login page automatically. This work is done thanks to middleware of keycloak npm module added to express app, I have tried several ways but i failed.

Some help please.

Thank you in advance.

**Comment by ferrerojosh** [comment]
This adapter was designed with NestJS in mind, by default Nest doesn't serve static pages but mainly do Restful APIs.

The idea is that you have a frontend that contacts your keycloak instance for an access token, and a backend (which in this case Nest) that contacts your keycloak instance if it is authorized to proceed with the request (AuthZ). This is all possible due to the OAuth 2.0 specification.

You could create a frontend around [keycloak-js](https://www.npmjs.com/package/keycloak-js) (which does the heavy lifting for you, i.e redirect you to keycloak login and securely store the access token in the keycloak instance using a cookie which tracks your session)

A full documentation of the keycloak javascript (for frontend clients) can be found [here](https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/oidc/javascript-adapter.adoc).

**Comment by rordenerena** [comment]
Ok, I got it, thank your for your explanation.

Both, backend and frontend applications are owned by me, then I think that I prefer to get a cookie session with the frontend and, by other hand, the backend will be the only one to contact with keycloak instance in order to set the maximum security context, as well as how says the keycloak book as the best security implementation. 

Or maybe I think about this ... because nest likes me more than nodejs for api rest :-)

One more time, thank you for your response.
